supabase-community/supabase-on-aws

- .github/workflows/publish.yml
> fix: fix synth command

- test/__snapshots__/main.test.ts.snap
> fix: update test snap

- .github/workflows/cfn-publish-stable.yml
- .github/workflows/cfn-publish.yml
- .github/workflows/ecr-publish.yml
> chore: update workflow name

- src/supabase-db.ts
- test/__snapshots__/main.test.ts.snap
> fix: added the comma to the exclude characters

- src/aws-amplify-hosting.ts
- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
Update default version of Studio to v0.23.04
> feat: Update Studio to v0.23.04

- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> fix: update default container image

- src/ecs-patterns.ts
- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> feat: Support clustering of realtime API

- src/aws-amplify-hosting.ts
- src/supabase-db/index.ts
- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> chore: Add comments

- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> fix: CFn Parameter Group - Security

- src/aws-workmail/cr-workmail-org.ts
- src/aws-workmail/cr-workmail-user.ts
- src/aws-workmail/index.ts
- test/__snapshots__/main.test.ts.snap
> chore: refactoring about the workmail construct

- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> fix: default realtime image

- src/ecs-patterns.ts
- src/supabase-cdn/index.ts
- src/supabase-db/index.ts
- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
HighAvailability option was added and database and containers are configured accordingly it.
This is to reduce the number of CloudFormation parameters and simplify it as much as possible.
> feat: Add HighAvailability option

- src/aws-amplify-hosting.ts
- src/supabase-stack.ts
- src/supabase-studio.ts
- test/__snapshots__/main.test.ts.snap
> feat: fix static credentials for Studio

- .github/workflows/cfn-publish-stable.yml
- .github/workflows/cfn-publish.yml
- src/ecs-patterns.ts
- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
ECS ServiceConnect is currently not supported in some regions, such as ap-south-1. #60
Also it is not required for Supabase and I will disable it.
> fix: Disable ECS ServiceConnect

- README.md
> chore: add quicklink for ap-south-1

- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> fix: update DNS_NODES

- README.md
This pull request enhances the Supabase Studio deployment information and adds an important security warning to ensure a safer deployment.
#70
> chore: Enhance Supabase Studio Deployment with Security Warning

- .github/workflows/waf-cfn-publish.yml
> fix: bug at actions

- containers/kong/Dockerfile
- containers/kong/kong-template.yml
- src/supabase-stack.ts
- test/__snapshots__/main.test.ts.snap
> feat: support edge-functions

- containers/kong/Dockerfile
> chore: kong base image
